version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "devDependencies"
    allow:
      - dependency-name: "@emailjs/browser"
        version-strategy: "auto"
      - dependency-name: "framer-motion"
        version-strategy: "auto"
      - dependency-name: "react"
        version-strategy: "auto"
      - dependency-name: "react-dom"
        version-strategy: "auto"
      - dependency-name: "react-type-animation"
        version-strategy: "auto"
      - dependency-name: "swiper"
        version-strategy: "auto"
      - dependency-name: "@eslint/js"
        version-strategy: "auto"
      - dependency-name: "@types/react"
        version-strategy: "auto"
      - dependency-name: "@types/react-dom"
        version-strategy: "auto"
      - dependency-name: "@vitejs/plugin-react"
        version-strategy: "auto"
      - dependency-name: "eslint"
        version-strategy: "auto"
      - dependency-name: "eslint-plugin-react"
        version-strategy: "auto"
      - dependency-name: "eslint-plugin-react-hooks"
        version-strategy: "auto"
      - dependency-name: "eslint-plugin-react-refresh"
        version-strategy: "auto"
      - dependency-name: "globals"
        version-strategy: "auto"
      - dependency-name: "vite"
        version-strategy: "auto"
    ignore:
      - dependency-name: "react"
        versions: ["^18.0.0"]
      - dependency-name: "react-dom"
        versions: ["^18.0.0"]
