version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "devDependencies"
    allow:
      - dependency-name: "@emailjs/browser"
      - dependency-name: "framer-motion"
      - dependency-name: "react"
      - dependency-name: "react-dom"
      - dependency-name: "react-type-animation"
      - dependency-name: "swiper"
      - dependency-name: "@eslint/js"
      - dependency-name: "@types/react"
      - dependency-name: "@types/react-dom"
      - dependency-name: "@vitejs/plugin-react"

      - dependency-name: "eslint"
      - dependency-name: "eslint-plugin-react"
      - dependency-name: "eslint-plugin-react-hooks"
      - dependency-name: "eslint-plugin-react-refresh"
      - dependency-name: "globals"
      - dependency-name: "vite"

